### ISSUE TITLE
React native - StreamVideoRN.setPushConfig() setBackgroundMessageHandler conflict

### ISSUE THREAD

**Issue by bohdan145** [GetStream/stream-video-js#1447]
**Which package/packages do you use?**

- [ ] `@stream-io/video-react-sdk`
- [x] `@stream-io/video-react-native-sdk`
- [ ] `@stream-io/video-client`

**Describe the bug**
In my app I use react-native-firebase to handle notifications logic 
in my index.js  I declare setBackgroundMessageHandler to handle background notification logic 
But when I initialize StreamVideoRN.setPushConfig() it also creates its own setBackgroundMessageHandler, so my previous setBackgroundMessageHandler index.js logic does not work anymore.
Is it possible to preserve my original logic in setBackgroundMessageHandler and also use StreamVideoRN setBackgroundMessageHandler?

**Version**

- SDK version: 0.9.2

**Env:**
Production

**React Native**

- OS: android, ios
- emulator and real device

**Comment by oliverlaz** [comment]
hi @bohdan145, thank you for reporting this issue. We'll take a look and we'll get back to you.
cc: @santhoshvai

**Comment by santhoshvai** [comment]
Hi @bohdan145 

Starting from 1.3.0 the SDK has support for adding notification handlers from your side instead of the SDK setting them up automatically. This would solve your problem.
 
The updated docs: https://getstream.io/video/docs/react-native/advanced/push-notifications/ringing-setup/react-native/#add-firebase-message-handlers
